# Generated by Django 3.2.8 on 2021-10-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211016_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='textEditor',
        ),
    ]
